name: Workflow CI/CD Pipeline
on:
  push:
    branches:
      - feat-gh-actions
    paths:
      - 'srv/**'
      - 'db/**'
      - 'security/**'
      - 'i18n/**'
      - '.github/workflows/**'
      - package.json
      - mta.yml
      - README.md
jobs:
  continuous-integration:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Set up NodeJS 18
        uses: actions/setup-java@v4
        with:
          node-version: '18'
          cache: 'npm'
      - name: Install dependences
        run: npm i
      - name: Run tests
        run: npm test
  continuous-delivery:
    needs: ["continuous-integration"]
    runs-on: ubuntu-latest
    steps:
      - run: echo "TODO Deploy to Cloud Foundry"
